[tool.poetry]
name = "videoutils"
version = "1.0.0"
description = "Fast & Simple Video Processing"
authors = ["hapatapa"]

[tool.poetry.dependencies]
python = "^3.11"
flet = "0.80.2"
flet-video = "0.80.2"
playsound = "1.2.2"
PyGObject = "3.48.2"
httpcore = ">=1.0.8"
httpx = ">=0.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
